/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAnchor: typeof import('naive-ui')['NAnchor']
    NAnchorLink: typeof import('naive-ui')['NAnchorLink']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCol: typeof import('naive-ui')['NCol']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NRow: typeof import('naive-ui')['NRow']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('@/ui/SvgIcon.vue')['default']
  }
}

// For TSX support
declare global {
  const NAnchor: (typeof import('naive-ui'))['NAnchor']
  const NAnchorLink: (typeof import('naive-ui'))['NAnchorLink']
  const NAvatar: (typeof import('naive-ui'))['NAvatar']
  const NButton: (typeof import('naive-ui'))['NButton']
  const NButtonGroup: (typeof import('naive-ui'))['NButtonGroup']
  const NCol: (typeof import('naive-ui'))['NCol']
  const NDivider: (typeof import('naive-ui'))['NDivider']
  const NForm: (typeof import('naive-ui'))['NForm']
  const NFormItem: (typeof import('naive-ui'))['NFormItem']
  const NIcon: (typeof import('naive-ui'))['NIcon']
  const NInput: (typeof import('naive-ui'))['NInput']
  const NLayout: (typeof import('naive-ui'))['NLayout']
  const NLayoutContent: (typeof import('naive-ui'))['NLayoutContent']
  const NLayoutFooter: (typeof import('naive-ui'))['NLayoutFooter']
  const NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader']
  const NLayoutSider: (typeof import('naive-ui'))['NLayoutSider']
  const NMenu: (typeof import('naive-ui'))['NMenu']
  const NRow: (typeof import('naive-ui'))['NRow']
  const NScrollbar: (typeof import('naive-ui'))['NScrollbar']
  const NTab: (typeof import('naive-ui'))['NTab']
  const NTabs: (typeof import('naive-ui'))['NTabs']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const SvgIcon: (typeof import('@/ui/SvgIcon.vue'))['default']
}
