/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
  }
}

// For TSX support
declare global {
  const NAvatar: (typeof import('naive-ui'))['NAvatar']
  const NButton: (typeof import('naive-ui'))['NButton']
  const NButtonGroup: (typeof import('naive-ui'))['NButtonGroup']
  const NDivider: (typeof import('naive-ui'))['NDivider']
  const NIcon: (typeof import('naive-ui'))['NIcon']
  const NLayout: (typeof import('naive-ui'))['NLayout']
  const NLayoutContent: (typeof import('naive-ui'))['NLayoutContent']
  const NLayoutFooter: (typeof import('naive-ui'))['NLayoutFooter']
  const NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader']
  const NLayoutSider: (typeof import('naive-ui'))['NLayoutSider']
  const NMenu: (typeof import('naive-ui'))['NMenu']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const SvgIcon: (typeof import('./../components/SvgIcon.vue'))['default']
}
